// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJsONMnn5Q2MOHUv0ztcoZBQaGuWR6f4',
    appId: '1:211575704292:web:ea7e73f0ed1e1c44563af1',
    messagingSenderId: '211575704292',
    projectId: 'campus-buddy-5deb5',
    authDomain: 'campus-buddy-5deb5.firebaseapp.com',
    storageBucket: 'campus-buddy-5deb5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqDw6JHGdWVqqN9_LIhpPdD2IDwhJhNJk',
    appId: '1:211575704292:android:548a7a08435b9a39563af1',
    messagingSenderId: '211575704292',
    projectId: 'campus-buddy-5deb5',
    storageBucket: 'campus-buddy-5deb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5vUIwT8omdOW5iddkLqoIrN_jsMxQTh8',
    appId: '1:211575704292:ios:fceeb42460e68087563af1',
    messagingSenderId: '211575704292',
    projectId: 'campus-buddy-5deb5',
    storageBucket: 'campus-buddy-5deb5.appspot.com',
    iosBundleId: 'com.example.campusBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5vUIwT8omdOW5iddkLqoIrN_jsMxQTh8',
    appId: '1:211575704292:ios:fceeb42460e68087563af1',
    messagingSenderId: '211575704292',
    projectId: 'campus-buddy-5deb5',
    storageBucket: 'campus-buddy-5deb5.appspot.com',
    iosBundleId: 'com.example.campusBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJsONMnn5Q2MOHUv0ztcoZBQaGuWR6f4',
    appId: '1:211575704292:web:5b9219e13a62f390563af1',
    messagingSenderId: '211575704292',
    projectId: 'campus-buddy-5deb5',
    authDomain: 'campus-buddy-5deb5.firebaseapp.com',
    storageBucket: 'campus-buddy-5deb5.appspot.com',
  );

}